# Generated by Django 5.0.4 on 2024-09-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularcourse',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
