# Generated by Django 5.0.4 on 2024-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_popularcourse_options_popularcourse_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='popularcourse',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='popularcourse',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
