# Generated by Django 5.0.4 on 2024-11-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='popularcourse',
            name='price',
        ),
    ]
