# Generated by Django 5.0.4 on 2024-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_event_image_url_remove_event_local_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.DeleteModel(
            name='ReviewTranslation',
        ),
    ]
