# Generated by Django 5.0.4 on 2024-11-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_comment_alter_review_local_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularcoursetranslation',
            name='certification',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes'),
        ),
    ]
