# Generated by Django 5.0.4 on 2024-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_popularcourse_lectures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='booked_slots',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_slots',
        ),
        migrations.AddField(
            model_name='teamtranslation',
            name='role',
            field=models.CharField(default='Default role', max_length=255),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='text',
            field=models.CharField(default='Default text', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='description',
            field=models.CharField(default='Default description', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='place',
            field=models.CharField(default='Default place', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
        ),
        migrations.AlterField(
            model_name='lessoninfotranslation',
            name='title',
            field=models.CharField(default='Default title', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, default='https://eduma.thimpress.com/wp-content/uploads/2022/07/thumnail-cate-7-170x170.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, default='https://eduma.thimpress.com/wp-content/uploads/2022/07/thumnail-cate-7-170x170.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamtranslation',
            name='desc',
            field=models.TextField(default='Default desc'),
        ),
        migrations.AlterField(
            model_name='teamtranslation',
            name='name',
            field=models.CharField(default='Default name', max_length=255),
        ),
    ]
