# Generated by Django 5.0.4 on 2024-11-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoninfo',
            name='count',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='icon',
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='image_url',
            field=models.URLField(blank=True, default='https://eduma.thimpress.com/wp-content/uploads/2022/07/thumnail-cate-7-170x170.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
