# Generated by Django 5.0.4 on 2024-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_name_contactmessage_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninfo',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
