# Generated by Django 5.0.4 on 2024-11-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_lessoninfo_local_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoninfo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lessoninfo',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
