# Generated by Django 5.0.4 on 2024-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_lessoninfo_options_lessoninfo_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninfo',
            name='local_image',
            field=models.FileField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
