# Generated by Django 5.0.4 on 2024-11-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_lessoninfo_local_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninfo',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
